# Generated by Django 4.2.6 on 2023-10-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonestore', '0003_tag_order_customer_order_phone_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='phonestore.tag'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('delivred', 'delivred'), ('Out of order', 'Out of order'), ('pending', 'pending')], max_length=100, null=True),
        ),
    ]
