# Generated by Django 4.2.6 on 2023-10-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonestore', '0004_order_tags_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='tags',
            field=models.ManyToManyField(to='phonestore.tag'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivred', 'delivred'), ('pending', 'pending'), ('Out of order', 'Out of order'), ('in progress', 'in progress')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('Out of order', 'Out of order'), ('availabe', 'availabe')], max_length=100, null=True),
        ),
    ]
