# Generated by Django 4.2.6 on 2023-10-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonestore', '0006_customer_user_alter_order_customer_alter_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('pending', 'pending'), ('delivred', 'delivred'), ('Out of order', 'Out of order')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('availabe', 'availabe'), ('Out of order', 'Out of order')], max_length=100, null=True),
        ),
    ]
