# Generated by Django 4.2.6 on 2023-10-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonestore', '0007_customer_photo_alter_order_status_alter_phone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='wallpaper1.jpg', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivred', 'delivred'), ('pending', 'pending'), ('Out of order', 'Out of order'), ('in progress', 'in progress')], max_length=100, null=True),
        ),
    ]
