# Generated by Django 4.2.6 on 2023-10-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonestore', '0012_alter_customer_photo_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in progress', 'in progress'), ('delivred', 'delivred'), ('Out of order', 'Out of order')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('availabe', 'availabe'), ('Out of order', 'Out of order')], max_length=100, null=True),
        ),
    ]
