# Generated by Django 4.2.6 on 2023-10-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonestore', '0013_alter_customer_email_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivred', 'delivred'), ('in progress', 'in progress'), ('pending', 'pending'), ('Out of order', 'Out of order')], max_length=100, null=True),
        ),
    ]
